name: Callable workflow
on:
  workflow_call:
    inputs:
      cmd:
        type: string
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          FILE=$(mktemp) 
          cat <<EOF > $FILE
          ${{ inputs.cmd }}
          EOF
         
          wc -c "$FILE" 

          if [[ $(wc -c "$FILE") -eq 0 ]]; then
            echo "No command given"
          else
            cat $FILE | sh
          fi
