name: Callable workflow
on:
  workflow_call:
    secrets:
      PASSWORD:
        required: false
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo hello!
          if [[ ${{ secrets.PASSWORD }} = "cornflakes" ]]; then
            echo "login successful"
          else
            echo "login unsuccessful"
          fi
