name: Callable workflow
on:
  workflow_call:
    inputs:
      cmd:
        type: string
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          cat <<EOF | sh 
          ${{ inputs.cmd }}
          EOF
