name: Main
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  multiline:
    uses: ./.github/workflows/callable.yml
    with:
      cmd: |
        echo hello
        echo world
  nocmd:
    uses: ./.github/workflows/callable.yml
